### ISSUE TITLE
Duvida 

### ISSUE THREAD

**Issue by amaroamorim** [gustavoguanabara/projeto-site#16]
Cade o arquivo html e js pra alocar no link?

**Comment by amaroamorim** [comment]
![image](https://user-images.githubusercontent.com/92817366/140996691-c0d151d6-3c59-4d66-acce-ea88ed61e4f5.png)

**Comment by Josemar5** [comment]
Não colocaste o linke dentro Das aspaz

**Comment by victorramide** [comment]
Olá Amaro, verificando o código do Professor Guanabara eu percebi o seguinte trecho no arquivo "index.html" `<p><a href="curso-js.html">Acesse o curso de JavaScript</a></p>`.

Como o colega acima mencionou, você esqueceu de colocar a referência para a página desejada no _href_ da tag _"a"_, nesse caso em especial, basta referenciar a página _curso-js.html_.

Lembrando que caso essas páginas estivessem em outras pastas deve-se adiciona-la ao caminho do arquivo, por exemplo: `href="/pasta/curso-js.html"`.

Espero ter ajudado, bons estudos.
